### ISSUE TITLE
Error parsing XML file. Please ensure the file is in valid XML format.

### ISSUE THREAD

**Issue by ilyas-Essar** [psyray/nmap-viewer#4]
it can't pars large xml nmap format files. When i upload scan.xml file it errors "Error parsing XML file. Please ensure the file is in valid XML format." Even though the file is xml, i opend it using Zenmap and it works so i am not sure if it is nmap-viewer or something wrong with my xml file that can't open large file. 
Size: 84.6 MB
![image](https://github.com/user-attachments/assets/1c5befc1-cf5c-4b9c-a659-f6b76c99c8de)
![image](https://github.com/user-attachments/assets/4bebd6c9-082c-4f1a-ba6b-4d4d53969e99)

when i upload small nmap xml file, it works

**Comment by Arthur-91140** [comment]
I have the same problem.

**Comment by psyray** [comment]
Thanks for reporting, I will have a look

**Comment by psyray** [comment]
> it can't pars large xml nmap format files. When i upload scan.xml file it errors "Error parsing XML file. Please ensure the file is in valid XML format." Even though the file is xml, i opend it using Zenmap and it works so i am not sure if it is nmap-viewer or something wrong with my xml file that can't open large file. Size: 84.6 MB
> 
> when i upload small nmap xml file, it works

Tested a big XML file on Linux Debian with nodeJS 23.1.0, no problem

Is there a way to provide the XML file in private ?
And also what's your operating system, nodeJS version ... ?
@igibi1791 same question

**Comment by psyray** [comment]
I've pushed a fix, with more error detection & feedback to user and some enhancements
Test it and give me some feedback here
`./nmap-viewer.sh update`
